# Generated by Django 3.0.3 on 2020-02-06 18:52

import apps.abogado.models.persona
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abogado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nacimiento', models.DateField()),
                ('ocupacion', models.CharField(max_length=50)),
                ('contact_info', django.contrib.postgres.fields.jsonb.JSONField(default=apps.abogado.models.persona.Persona.contact_default, verbose_name='ContactInfo')),
                ('abogado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
