# Generated by Django 3.0.3 on 2020-02-15 23:00

import apps.abogado.models.empresa
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abogado', '0004_auto_20200209_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='persona',
            name='abogado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FloatField()),
                ('nombre', models.CharField(max_length=50)),
                ('actividad', models.CharField(max_length=50)),
                ('contact_info', django.contrib.postgres.fields.jsonb.JSONField(default=apps.abogado.models.empresa.Empresa.contact_default, verbose_name='ContactInfo')),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
