# Generated by Django 3.0.3 on 2020-02-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceso',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('asignar_permisos', 'Asigna permisos sobre el objeto'), ('ver_proceso', 'ver todo del proceso'), ('agregar_archivos', 'agregar archivos'), ('modificar_archivos', 'modificar archivos'), ('eliminar_archivos', 'eliminar archivos'), ('agregar_notificacion', 'agregar notificacion'), ('modificar_notificacion', 'modificar notificacion'), ('eliminar_notificacion', 'eliminar notificacion'), ('agregar_actuacion', 'agregar actuacion'), ('modificar_actuacion', 'modificar actuacion'), ('eliminar_actuacion', 'eliminar actuacion'), ('agregar_cautela', 'agregar cautela'), ('modificar_cautela', 'modificar cautela'), ('eliminar_cautela', 'eliminar cautela'))},
        ),
    ]
