# Generated by Django 3.0.3 on 2020-02-13 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0003_proceso_abogado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuacion',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proceso.Proceso'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proceso.Proceso'),
        ),
        migrations.AlterField(
            model_name='cautelar',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proceso.Proceso'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proceso.Proceso'),
        ),
    ]
