# Generated by Django 3.0.3 on 2020-02-15 23:00

import apps.proceso.models.ejecutivo
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abogado', '0005_auto_20200215_1800'),
        ('proceso', '0004_auto_20200213_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejecutivo',
            name='pretencion',
        ),
        migrations.AddField(
            model_name='ejecutivo',
            name='contact_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=apps.proceso.models.ejecutivo.Ejecutivo.pretencion_default, verbose_name='ContactInfo'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='litisconsorcio',
            field=models.CharField(choices=[('NECESARIO', 'necesario'), ('FACULTATIVO', 'facultativo'), ('CUASI-NECESARIO', 'cuasi-necesario'), ('NO-APLICA', 'no aplica')], default='NO-APLICA', max_length=30),
        ),
        migrations.CreateModel(
            name='Partesn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('DEMANDADO', 'demandado'), ('DEMANDANTE', 'demandante'), ('PERITO', 'perito'), ('TERCERO', 'tercero')], default='DEMANDANTE', max_length=15)),
                ('Proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proceso.Proceso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abogado.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Partesj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('DEMANDADO', 'demandado'), ('DEMANDANTE', 'demandante')], default='DEMANDANTE', max_length=15)),
                ('Proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proceso.Proceso')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abogado.Empresa')),
            ],
        ),
    ]
