# Generated by Django 3.0.3 on 2020-02-13 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(default='santander', max_length=50)),
                ('ciudad', models.CharField(default='bucaramanga', max_length=50)),
                ('corporacion', models.CharField(default='juzgado de circuito 31', max_length=50)),
                ('especialidad', models.CharField(default='penal', max_length=50)),
                ('despacho', models.CharField(default='juzgado de circuito penal 01', max_length=100)),
                ('direccion', models.CharField(default='avenida siempre viva 742', max_length=100)),
                ('telefono', models.CharField(default='666', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('documento', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('despacho', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='despacho.Despacho')),
            ],
        ),
    ]
